### ISSUE TITLE
Add reload command for config files

### ISSUE THREAD

**Issue by reyes256** [Athlaeos/ValhallaMMO#19]
Need to restart the whole server just to change the language

**Comment by Athlaeos** [comment]
Hi, sorry, but I'll be honest and say that the reason there's no reload command yet is because I'm notoriously bad at making them, and so I'm reluctant to add one yet because it's probably just going to end up crashing the server. The plugin is rather big, after all. I don't know when or if I'll be adding one. In the meantime though, Plugman seems to do a good job at reloading the plugin
