### ISSUE TITLE
Drill ability not working after latest update

### ISSUE THREAD

**Issue by LichGirl** [Athlaeos/ValhallaMMO#25]
My players are having issues using the drill ability after the latest update to your plugin - any way I can test/fix that?

**Comment by LichGirl** [comment]
The ability activates but does not do anything

**Comment by Athlaeos** [comment]
It's a known bug, I just haven't gotten around to testing it yet. thanks for reporting still though!

**Comment by Athlaeos** [comment]
I've looked into it a bit more, and as it turns out it still works, but the effect is just often too small to notice. In a recent update I fixed an issue where the buff from drilling was applying twice, thereby making it feel like it actually does something. The reason it doesn't feel like it does as much is because the buff works additive with your other mining speed multipliers, not multiplicative. So I just changed it so it's multiplicative, but it's not significant enough of a change to push an update for. If you like, you can get this version on my discord server
