### ISSUE TITLE
[Feat] Perk Respec

### ISSUE THREAD

**Issue by SlyCedix** [Athlaeos/ValhallaMMO#7]
The ability to refund the cost of a perk via a resource cost (or free, in the case of my server).

The documentation is a bit limited so I actually thought that the option forgettable_perks was this, until I looked at the code.

**Comment by Athlaeos** [comment]
that seems very specific, why do you want to refund specifically a perk's cost? can't you make the perk free instead?

**Comment by SlyCedix** [comment]
I actually just want players to be able to experiment with things without permanently committing to the perks they select. Say, they stop using light armor and switch to heavy armor, they can refund the light armor tree and reallocate those skill points.

**Comment by Athlaeos** [comment]
Well, there's a reset type for that actually. If you do /val reset you get a couple of options, one of which is skills_refund_exp, and it resets a players skills but refunds exp so you don't lose progress but you get all your skill points back and such. Though it does every skill, you can't specify a skill to do this specifically on. 
I'm probably not going to implement a skill-specific refunding reset type like you ask because it's such a hyperspecific use case that basically nobody will be using
